# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-27 01:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_survey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='q_imporant_find_cancer',
            field=models.CharField(blank=True, choices=[('Very Concerned', 'Very Concerned'), ('Somewhat Concerned', 'Somewhat Concerned'), ('Not Concerned', 'Not Concerned')], max_length=50, null=True),
        ),
    ]
