# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-27 02:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20160726_2043'),
    ]

    operations = [
        migrations.RenameField(
            model_name='survey',
            old_name='q_imporant_find_cancer',
            new_name='q_important_find_cancer',
        ),
        migrations.AlterField(
            model_name='survey',
            name='q_concerned_false_alarm',
            field=models.CharField(blank=True, choices=[('Very Concerned', 'Very Concerned'), ('Somewhat Concerned', 'Somewhat Concerned'), ('Not Concerned', 'Not Concerned')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='q_concerned_radiation',
            field=models.CharField(blank=True, choices=[('Very Concerned', 'Very Concerned'), ('Somewhat Concerned', 'Somewhat Concerned'), ('Not Concerned', 'Not Concerned')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='q_concerned_surgery',
            field=models.CharField(blank=True, choices=[('Very Concerned', 'Very Concerned'), ('Somewhat Concerned', 'Somewhat Concerned'), ('Not Concerned', 'Not Concerned')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='q_concerned_unnecessary_treatment',
            field=models.CharField(blank=True, choices=[('Very Concerned', 'Very Concerned'), ('Somewhat Concerned', 'Somewhat Concerned'), ('Not Concerned', 'Not Concerned')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='q_confirm',
            field=models.CharField(blank=True, choices=[('quit smoking', 'The best thing to lower your risk of dying from lung cancer is to quit smoking or continue to not smoke.'), ('annual screening', 'I should return once a year for annual screening.')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='q_talk_having_surgery',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes, I want to talk about this'), ('No', 'No, I dont want to talk about this')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='q_talk_how_soon',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes, I want to talk about this'), ('No', 'No, I dont want to talk about this')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='q_talk_more_screening',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes, I want to talk about this'), ('No', 'No, I dont want to talk about this')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='q_talk_not_screened',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes, I want to talk about this'), ('No', 'No, I dont want to talk about this')], max_length=50, null=True),
        ),
    ]
