# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-27 02:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_auto_20160726_2106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='q_important_find_cancer',
        ),
        migrations.AddField(
            model_name='survey',
            name='q_concerned_find_cancer',
            field=models.CharField(blank=True, choices=[('Very Concerned', 'Very Concerned'), ('Somewhat Concerned', 'Somewhat Concerned'), ('Not Concerned', 'Not Concerned')], max_length=50, null=True, verbose_name='How important is it to you to find lung cancer early when it may be treated more easily treated?'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='q_concerned_false_alarm',
            field=models.CharField(blank=True, choices=[('Very Concerned', 'Very Concerned'), ('Somewhat Concerned', 'Somewhat Concerned'), ('Not Concerned', 'Not Concerned')], max_length=50, null=True, verbose_name='having a false alarm?'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='q_concerned_radiation',
            field=models.CharField(blank=True, choices=[('Very Concerned', 'Very Concerned'), ('Somewhat Concerned', 'Somewhat Concerned'), ('Not Concerned', 'Not Concerned')], max_length=50, null=True, verbose_name='being exposed to radiation from lung cancer?'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='q_concerned_surgery',
            field=models.CharField(blank=True, choices=[('Very Concerned', 'Very Concerned'), ('Somewhat Concerned', 'Somewhat Concerned'), ('Not Concerned', 'Not Concerned')], max_length=50, null=True, verbose_name='having surgery if lung cancer is found?'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='q_concerned_unnecessary_treatment',
            field=models.CharField(blank=True, choices=[('Very Concerned', 'Very Concerned'), ('Somewhat Concerned', 'Somewhat Concerned'), ('Not Concerned', 'Not Concerned')], max_length=50, null=True, verbose_name='being treated for lung cancer that never would have harmed you?'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='q_confirm',
            field=models.CharField(blank=True, choices=[('quit smoking', 'The best thing to lower your risk of dying from lung cancer is to quit smoking or continue to not smoke.'), ('annual screening', 'I should return once a year for annual screening.')], max_length=50, null=True, verbose_name='Before you talk to your provider, please confirm the comments below:'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='q_talk_having_surgery',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes, I want to talk about this'), ('No', 'No, I dont want to talk about this')], max_length=50, null=True, verbose_name='having surgery if lung cancer is found?'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='q_talk_how_soon',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes, I want to talk about this'), ('No', 'No, I dont want to talk about this')], max_length=50, null=True, verbose_name='how soon I will know the results of screening.'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='q_talk_more_screening',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes, I want to talk about this'), ('No', 'No, I dont want to talk about this')], max_length=50, null=True, verbose_name='what happens if the lung cancer screening shows something that may need more testing.'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='q_talk_not_screened',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes, I want to talk about this'), ('No', 'No, I dont want to talk about this')], max_length=50, null=True, verbose_name='what happens if I decide NOT to be screened for lung cancer.'),
        ),
    ]
